name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Screenshots
        
        If applicable, add screenshots after opening the issue.
  - type: textarea
    attributes:
      label: "Desktop"
      description: "please complete the following information"
      placeholder: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Smartphone"
      description: "please complete the following information"
      placeholder: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "References"
      description: "References to other issues (Trello / GitLab etc.)"
    validations:
      required: false
