on:
  push:
    branches:
      - "main"

name: "Main Branch"

# Secrets:
# * JM_GITLAB_REF - Branch to trigger CI on. (Even though the name includes "ref", GitLab does only allow branch names)
# * JM_GITLAB_TOKEN - Auth token to trigger GitLab CI
# * JM_GITLAB_URL - CI Trigger URL

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml
    with:
      dockerTag: "${{ github.ref_name }}"

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  deploy:
    name: "Deploy"

    needs: ['build']

    uses: ./.github/workflows/part_deploy.yml
    with:
      environment: development
    secrets:
      JM_GITLAB_TOKEN: ${{ secrets.JM_GITLAB_TOKEN }}
      JM_GITLAB_REF: ${{ secrets.JM_GITLAB_REF }}
      JM_GITLAB_URL: ${{ secrets.JM_GITLAB_URL }}