on:
  workflow_call:
    outputs:
      elixirVersion:
        description: "The .tool-versions Elixir version"
        value: "${{ jobs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion:
        description: "The .tool-versions OTP version"
        value: "${{ jobs.detectToolVersions.outputs.otpVersion }}"
      nodeVersion:
        description: "The .tool-versions Node.js version"
        value: "${{ jobs.detectToolVersions.outputs.nodeVersion }}"

name: "Detect Tool Versions"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      elixirVersion: "${{ env.ELIXIR_VERSION }}"
      otpVersion: "${{ env.OTP_VERSION }}"
      nodeVersion: "${{ env.NODE_VERSION }}"

    steps:
      - uses: actions/checkout@v3
      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          ELIXIR_VERSION="$(cat .tool-versions | grep elixir | cut -d' ' -f2- | sed 's/-otp-[0-9]*//')"
          echo Elixir: $ELIXIR_VERSION
          echo "ELIXIR_VERSION=${ELIXIR_VERSION}" >> $GITHUB_ENV

          OTP_VERSION="$(cat .tool-versions | grep erlang | cut -d' ' -f2-)"
          echo OTP: $OTP_VERSION
          echo "OTP_VERSION=${OTP_VERSION}" >> $GITHUB_ENV

          NODE_VERSION="$(cat .tool-versions | grep nodejs | cut -d' ' -f2-)"
          echo Node.js: $NODE_VERSION
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
