on:
  workflow_call:
    inputs:
      plugin:
        type: string
        required: true
      constraint:
        type: string
        default: ""
        required: false

name: "ASDF Update"

jobs:
  compile_assets:
    name: "${{ inputs.plugin }}"

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: ASDF Install
        uses: asdf-vm/actions/install@v2
      - name: "Get Newest Version"
        id: newestVersion
        run: |
          LATEST_VERSION=$(asdf latest "${{ inputs.plugin }}" "${{ inputs.constraint }}")
          echo "Latest (${{ inputs.constraint }}): $LATEST_VERSION"
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
      - name: "Try Installing new version"
        run: |
          asdf install "${{ inputs.plugin }}" "${{ env.LATEST_VERSION }}"
      - name: "Apply latest version to .tool-versions"
        run: |
          asdf local "${{ inputs.plugin }}" "${{ env.LATEST_VERSION }}"
      - uses: peter-evans/create-pull-request@v5
        with:
          add-paths: '.tool-versions'
          commit-message: 'Update ${{ inputs.plugin }} to ${{ env.LATEST_VERSION }}'
          title: 'Update ${{ inputs.plugin }} to ${{ env.LATEST_VERSION }}'
          branch: 'asdf/${{ inputs.plugin }}/${{ env.LATEST_VERSION }}'
          delete-branch: true
          labels: 'asdf,enhancement'
