on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

# Secrets:
# * JM_GITLAB_REF - Branch to trigger CI on. (Even though the name includes "ref", GitLab does only allow branch names)
# * JM_GITLAB_TOKEN - Auth token to trigger GitLab CI
# * JM_GITLAB_URL - CI Trigger URL

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml
    with:
      dockerBuild: false

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  dependabot:
    name: "Dependabot"

    if: ${{ github.actor == 'dependabot[bot]'}}

    uses: ./.github/workflows/part_dependabot.yml