on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+-beta.[0-9]+"

name: "Beta Tag"

# Secrets:
# * JM_GITLAB_REF - Branch to trigger CI on. (Even though the name includes "ref", GitLab does only allow branch names)
# * JM_GITLAB_TOKEN - Auth token to trigger GitLab CI
# * JM_GITLAB_URL - CI Trigger URL

jobs:
  release:
    name: "Release"

    uses: ./.github/workflows/part_release.yml
    with:
      releaseName: "${{ github.ref_name }}"

  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml
    with:
      dockerTag: "${{ github.ref_name }}"

  docs:
    name: "Docs"

    needs: ['release']

    uses: ./.github/workflows/part_docs.yml
    with:
      releaseName: "${{ github.ref_name }}"

  deploy:
    name: "Deploy"

    needs: ['build']

    uses: ./.github/workflows/part_deploy.yml
    with:
      environment: staging
      version: "${{ github.ref_name }}"
    secrets:
      JM_GITLAB_TOKEN: ${{ secrets.JM_GITLAB_TOKEN }}
      JM_GITLAB_REF: ${{ secrets.JM_GITLAB_REF }}
      JM_GITLAB_URL: ${{ secrets.JM_GITLAB_URL }}
